# 项目级 pip 配置，可通过环境变量 PIP_CONFIG_FILE=./pip.conf 启用
# 也可复制到 ~/.pip/pip.conf 或 ~/.config/pip/pip.conf 作为用户全局配置

[global]
index-url = https://pypi.tuna.tsinghua.edu.cn/simple
trusted-host = pypi.tuna.tsinghua.edu.cn
